name: "Playwright Tests"

env:
  BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}

on:
  pull_request:
    branches: main

jobs:
  verify_pr_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge to main from development."
          exit 1

  playwright-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: verify_pr_branch
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run test #Wait for deployment to complete and run Playwright tests
        env:
          NODE_ENV: preview
        run: |
          PREVIEW_URL="https://preview${BASE_DOMAIN}"
          echo "wait-on will now wait for $PREVIEW_URL to be ready"
          npx wait-on $PREVIEW_URL && PREVIEW_URL=$PREVIEW_URL npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
